/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#05050a',
        'on-primary': '#ffffff',
        'primary-container': '#1e1e24',
        'on-primary-container': '#87858d',
        'primary-fixed': '#e4e1ea',
        'primary-fixed-dim': '#c8c5cd',
        'on-primary-fixed': '#1b1b21',
        'on-primary-fixed-variant': '#47464d',
        secondary: '#4355b9',
        'on-secondary': '#ffffff',
        'secondary-container': '#8596ff',
        'on-secondary-container': '#11278e',
        'secondary-fixed': '#dee0ff',
        'secondary-fixed-dim': '#bac3ff',
        'on-secondary-fixed': '#00105c',
        'on-secondary-fixed-variant': '#293ca0',
        tertiary: '#070501',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#221e15',
        'on-tertiary-container': '#8c8579',
        'tertiary-fixed': '#ebe1d3',
        'tertiary-fixed-dim': '#cec5b7',
        'on-tertiary-fixed': '#1f1b12',
        'on-tertiary-fixed-variant': '#4b463c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#47464b',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#c8c5cd',
        outline: '#78767b',
        'outline-variant': '#c8c5cb',
        'surface-tint': '#5e5e65',
      },
      fontFamily: {
        h1: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        button: ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        button: ['15px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        gutter: '24px',
        unit: '4px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
